export { HomePage } from './HomePage'
export { ProductPage } from './ProductPage'
export { CartPage } from './CartPage'
export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
export { ShippingPage } from './ShippingPage'
export { PaymentPage } from './PaymentPage'
